version: '3'
services:
  frontend:
    # image: "peerprep15/peerprep15:frontend-latest"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    env_file:
      - .env