version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbitmq", "5672" ]
      interval: 5s
      timeout: 30s
      retries: 5

  matching-service:
    image: "peerprep15/peerprep15:matching-latest"
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure