version: '3'
services:
  user-service:
    image: "dsja612/se-toolbox:user-latest"
    ports:
      - "80:5000"
    environment:
      MONGOURL: "mongodb+srv://peerprep15:CRFVdZNswqisruzv@peerprep.vmiy632.mongodb.net/?retryWrites=true&w=majority" # Add MongoDB connection URL
      PG_USER: localuser
      PG_PASSWORD: 12345
      PG_DB: peerprep
      PG_HOST: user-db
    depends_on:
      - user-db

  user-db:
    image: "postgres:13"
    container_name: user-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: peerprep
    volumes:
      - user-data:/var/lib/postgresql/data

volumes:
  user-data: