name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:
    build_docker_images:
        name: build docker images
        runs-on: [ubuntu-latest]
        steps:
          - name: checkout
            uses: actions/checkout@v2

          - name: Docker Login
            uses: docker/login-action@v1.8.0
            with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
                logout: true
        
          - name: Build Server image
            run: docker build -t SE-Toolbox-CD-GH-Actions-AWS/Docker-test-env -f
                    ./Dockerfile ./
          - name: Tag our Image
            run: docker tag SE-Toolbox-CD-GH-Actions-AWS/Docker-test-env 
                    SE-Toolbox-CD-GH-Actions-AWS/Docker-test-env:latest
          - name: Push to dockerhub
            run: docker push SE-Toolbox-CD-GH-Actions-AWS/Docker-test-env
    
          - name: Deploy to EB
            uses: einaregilsson/beanstalk-deploy@v14
            with:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                application_name: Docker-test
                environment_name: Docker-test-env
                version_label: 1.0.1
                region: ap-southeast-1
